### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by jarbesfeld** [cancervariants/uta-tools#70]
I am running the following the command within FUSOR to create a transcript segment component object:

transcript_segment_component(tx_to_genomic_coords = False, chromosome = 1, strand = 1, start = 3629865, gene = 'TPRG1L')

and get the following error:

File ~/fusor_work/venv/lib/python3.10/site-packages/uta_tools/uta_tools.py:420, in UTATools._set_mane_genomic_data(self, params, gene, alt_ac, pos, strand, is_start, residue_mode)
    418 tx_pos = mane_data["pos"][0] + mane_data["coding_start_site"]
    419 params["exon"] = self._get_exon_number(tx_exons, tx_pos)
--> 420 tx_exon = tx_exons[params["exon"] - 1]
    421 strand_to_use = strand if strand is not None else mane_data["strand"]
    422 params["strand"] = strand_to_use

IndexError: list index out of range

**Comment by korikuzma** [comment]
These are the parameters being passed to `uta_tools.genomic_to_transcript_exon_coordinates`
```json
{"chromosome": 1, "strand": 1, "start": 3629864, "gene": "TPRG1L", "residue_mode": "inter-residue"}
```
